sudo: required
services: 
  - docker

before_install:
  - docker build -t krunalyadav/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krunalyadav/docker-react npm run test -- --coverage